import { Screens } from "../themes";
import { LocalImages } from "./imageUrlConstants";
import { SCREENS } from "./Labels";
export const ABOUT_ROUTES = {
  MY_PROFILE: {
    CARD: "myProfile",
    TITLE: SCREENS.DRAWERMENUTITLES.MY_PROFILE,
    URI: LocalImages.profileImage,
    RIGHT_ICON: LocalImages.sideArrowImage,
    SCREEN: "ProfileScreen",
    COLOR: "#D7EFFB",
  },
  // HOME: {
  //   CARD: "UserAgreement",
  //   TITLE: SCREENS.DRAWERMENUTITLES.HOME,
  //   URI: LocalImages.homeImage,
  //   SCREEN: "Home",
  //   COLOR: "#FFDD9B",
  // },
  // DOCUMENT: {
  //   URI: LocalImages.documentpic,
  //   CARD: "MerchantAgreement",
  //   TITLE: SCREENS.DRAWERMENUTITLES.DOCUMENT,
  //   SCREEN: "Documents",
  //   COLOR: "#C5BDF6",
  // },
  // HISTORY: {
  //   URI: LocalImages.historyImage,
  //   CARD: "AcceptableUsePolicy",
  //   TITLE: SCREENS.DRAWERMENUTITLES.HISTORY,
  //   SCREEN: "History",
  //   COLOR: "#F6BDE9",
  // },
  SETTINGS: {
    RIGHT_ICON: LocalImages.sideArrowImage,
    URI: LocalImages.settingimage,
    CARD: "AcceptableUsePolicy",
    TITLE: SCREENS.DRAWERMENUTITLES.SETTING,
    SCREEN: "settings",
    COLOR: "#BFF5CE",
  },

  ABOUT: {
    URI: LocalImages.documentsImage,
    CARD: "AcceptableUsePolicy",
    TITLE: SCREENS.DRAWERMENUTITLES.ABOUT_US,
    SCREEN: "about",
    COLOR: "#FFAFAF",
  },
  // CONSENT: {
  //   URI: LocalImages.codeIcon,
  //   CARD: "AcceptableUsePolicy",
  //   TITLE: "Consent",
  //   SCREEN: "code",
  //   COLOR: "#ffcdb2",
  // },
  TERMS: {
    URI: LocalImages.termsImage,
    CARD: "AcceptableUsePolicy",
    TITLE: SCREENS.DRAWERMENUTITLES.TERM_CONDITION,
    SCREEN: "terms",
    COLOR: "#cce3de",
  },
  IDENTITY: {
    RIGHT_ICON: LocalImages.sideArrowImage,
    URI: LocalImages.backupicon,
    CARD: "AcceptableUsePolicy",
    TITLE: SCREENS.DRAWERMENUTITLES.BACKUP,
    SCREEN: "AuthBackupIdentity",
    COLOR: "#FFDD9B",
  },
  // PAYMENT: {
  //   RIGHT_ICON: LocalImages.sideArrowImage,
  //   URI: LocalImages.paymentshand,
  //   CARD: "Payment",
  //   TITLE: SCREENS.DRAWERMENUTITLES.PAYMENT,
  //   SCREEN: "Payment",
  //   COLOR: "#90EE90",
  // },
  DELETE: {
    URI: LocalImages.deleteImage,
    CARD: "AcceptableUsePolicy",
    TITLE: SCREENS.DRAWERMENUTITLES.DELETE_IDENTITY,
    SCREEN: "delete",
    COLOR: "#C5BDF6",
  },
  // LOGOUT: {
  //   URI: LocalImages.logoutImage,
  //   CARD: "AcceptableUsePolicy",
  //   TITLE: SCREENS.DRAWERMENUTITLES.LOGOUT,
  //   SCREEN: "Logout",
  //   COLOR: "#F6BDE9",
  // },
  // DEV: {
  //   RIGHT_ICON: LocalImages.sideArrowImage,
  //   URI: LocalImages.deleteImage,
  //   CARD: "Development",
  //   TITLE: "DEV",
  //   SCREEN: "Dev",
  //   COLOR: "#C5BDF6",
  // },
   CODE: {
    URI: LocalImages.codeIcon,
    CARD: "AcceptableUsePolicy",
    TITLE: "Have a Code?",
    SCREEN: "code",
    COLOR: "#ffcdb2",
  },
};

export const SETTING_LIST = [
  {
    CARD: "updateauthenticaion",
    TITLE: "updateauthenticaion",
    URI: LocalImages.securityImage,
    RIGHT_ICON: LocalImages.sideArrowImage,
    SCREEN: "ProfileScreen",
    COLOR: "#D7EFFB",
  },
  {
    CARD: "language",
    TITLE: "language",
    URI: LocalImages.translateImage,
    SCREEN: "Home",
    RIGHT_ICON: LocalImages.sideArrowImage,
    COLOR: "#FFDD9B",
  },
  {
    CARD: "consent",
    TITLE: "Consent",
    URI: LocalImages.termsImage,
    SCREEN: "Consent",
    RIGHT_ICON: LocalImages.sideArrowImage,
    COLOR: "#cce3de",
  },
  // {
  //   CARD: "backup",
  //   TITLE: "Backup & Recovery",
  //   URI: LocalImages.backupicon,
  //   SCREEN: "Dev4",
  //   RIGHT_ICON: LocalImages.sideArrowImage,
  //   COLOR: "#C5BDF6",
  // },
];
