# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, 14.0
prepare_react_native_project!
# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```


linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'GlobalId' do
  config = use_native_modules!
  $RNFirebaseAsStaticFramework = true
  pod 'ZXingObjC', '~> 3.1'

  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  # 'FaceDetectorMLKit'
]
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'GlobalIdTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
      react_native_post_install(
        installer,
        # Set `mac_catalyst_enabled` to `true` in order to apply patches
        # necessary for Mac Catalyst builds
        :mac_catalyst_enabled => false
      )
      # NOTE: Change IPHONEOS_DEPLOYMENT_TARGET to 12.4.
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
           config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
        
           config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
  
        end
      end

    end
end
target 'ShareExtension' do
  use_react_native!
  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
 # Manually link packages here to keep your extension bundle size minimal
end
